//! Golden tests: the Rust schedule/retry port against outputs generated from
//! the ccc Python reference (`agent_cron_lib.py`), including the DST gap,
//! the ambiguous fall-back hour, and the Asia/Seoul fixed offset.
//!
//! `fixtures/cron_golden.json` is generated by running the pure Python
//! reference over a fixed case list; do not hand-edit it.

use chrono::{DateTime, Utc};
use danso::cron::retry::{RetryPolicy, retry_delay, retry_view};
use danso::cron::schedule::{
    OCCURRENCE_SCAN_LIMIT, iter_occurrences, next_after, parse_schedule, schedule_occurrences,
};
use danso::cron::store::{RetryPolicySpec, RetryState};
use danso::cron::time::{fmt_dt, parse_utc};
use serde_json::Value;

const GOLDEN: &str = include_str!("fixtures/cron_golden.json");

fn fixture() -> Value {
    serde_json::from_str(GOLDEN).expect("valid golden fixture")
}

fn utc(raw: &str) -> DateTime<Utc> {
    parse_utc(Some(raw), "fixture")
        .expect("fixture timestamp")
        .expect("non-empty fixture timestamp")
}

#[test]
fn golden_iter_occurrences_matches_the_python_reference() {
    for case in fixture()["iterCases"].as_array().expect("iterCases") {
        let schedule = parse_schedule(
            case["schedule"].as_str().unwrap(),
            case["tz"].as_str().unwrap(),
        )
        .unwrap_or_else(|error| panic!("parse {:?}: {error}", case["schedule"]));
        let (occurrences, truncated) = iter_occurrences(
            &schedule,
            utc(case["start"].as_str().unwrap()),
            utc(case["end"].as_str().unwrap()),
            case["cap"].as_u64().unwrap_or(OCCURRENCE_SCAN_LIMIT as u64) as usize,
        );
        let expected: Vec<String> = case["expect"]
            .as_array()
            .expect("expect array")
            .iter()
            .map(|value| value.as_str().expect("ISO string").to_string())
            .collect();
        let actual: Vec<String> = occurrences
            .iter()
            .map(|dt| fmt_dt(Some(*dt)).expect("fmt"))
            .collect();
        assert_eq!(actual, expected, "iter {:?}", case["schedule"]);
        assert_eq!(
            truncated,
            case["truncated"].as_bool().unwrap(),
            "truncated {:?}",
            case["schedule"]
        );
    }
}

#[test]
fn golden_next_after_matches_the_python_reference() {
    for case in fixture()["nextCases"].as_array().expect("nextCases") {
        let schedule = parse_schedule(
            case["schedule"].as_str().unwrap(),
            case["tz"].as_str().unwrap(),
        )
        .unwrap_or_else(|error| panic!("parse {:?}: {error}", case["schedule"]));
        let anchor = case["anchor"].as_str().map(utc);
        let next = next_after(&schedule, utc(case["after"].as_str().unwrap()), anchor);
        let expected = case["expect"].as_str();
        assert_eq!(
            next.map(|dt| fmt_dt(Some(dt)).expect("fmt")),
            expected.map(str::to_string),
            "next_after {:?}",
            case["schedule"]
        );
    }
}

#[test]
fn golden_schedule_occurrences_matches_the_python_reference() {
    for case in fixture()["schedCases"].as_array().expect("schedCases") {
        let schedule = parse_schedule(
            case["schedule"].as_str().unwrap(),
            case["tz"].as_str().unwrap(),
        )
        .unwrap_or_else(|error| panic!("parse {:?}: {error}", case["schedule"]));
        let optional = |key: &str| case[key].as_str().map(utc);
        let (occurrences, truncated) = schedule_occurrences(
            &schedule,
            optional("last"),
            utc(case["at"].as_str().unwrap()),
            optional("anchor"),
            case["cap"].as_u64().unwrap_or(OCCURRENCE_SCAN_LIMIT as u64) as usize,
        );
        let expected: Vec<String> = case["expect"]
            .as_array()
            .expect("expect array")
            .iter()
            .map(|value| value.as_str().expect("ISO string").to_string())
            .collect();
        let actual: Vec<String> = occurrences
            .iter()
            .map(|dt| fmt_dt(Some(*dt)).expect("fmt"))
            .collect();
        assert_eq!(
            actual, expected,
            "schedule_occurrences {:?}",
            case["schedule"]
        );
        assert_eq!(
            truncated,
            case["truncated"].as_bool().unwrap(),
            "truncated {:?}",
            case["schedule"]
        );
    }
}

#[test]
fn golden_parse_errors_fail_closed_with_the_reference_message() {
    for case in fixture()["parseErrors"].as_array().expect("parseErrors") {
        let result = parse_schedule(
            case["schedule"].as_str().unwrap(),
            case["tz"].as_str().unwrap(),
        );
        let message = result.expect_err("expected parse failure");
        assert!(
            message.contains(case["expect_contains"].as_str().unwrap()),
            "message {message:?} does not mention {:?}",
            case["expect_contains"]
        );
    }
}

#[test]
fn golden_parse_ok_kinds_match_the_reference() {
    for case in fixture()["parseOk"].as_array().expect("parseOk") {
        let schedule = parse_schedule(
            case["schedule"].as_str().unwrap(),
            case["tz"].as_str().unwrap(),
        )
        .unwrap_or_else(|error| panic!("parse {:?}: {error}", case["schedule"]));
        assert_eq!(
            schedule.kind(),
            case["kind"].as_str().unwrap(),
            "{:?}",
            case["schedule"]
        );
    }
}

#[test]
fn golden_retry_policies_clamp_like_the_reference() {
    for case in fixture()["retryCases"].as_array().expect("retryCases") {
        let task = &case["task"];
        let spec: Option<RetryPolicySpec> = task
            .get("retryPolicy")
            .map(|raw| serde_json::from_value(raw.clone()).expect("retryPolicy shape"));
        let state: Option<RetryState> = task
            .get("retryState")
            .map(|raw| serde_json::from_value(raw.clone()).expect("retryState shape"));
        let policy = RetryPolicy::from_spec(spec.as_ref());
        let expected_policy = &case["policy"];
        assert_eq!(
            policy.max_attempts,
            expected_policy["maxAttempts"].as_i64().unwrap()
        );
        assert_eq!(
            policy.backoff_sec,
            expected_policy["backoffSec"].as_i64().unwrap()
        );
        assert_eq!(
            policy.multiplier,
            expected_policy["backoffMultiplier"].as_i64().unwrap()
        );
        assert_eq!(
            policy.max_backoff_sec,
            expected_policy["maxBackoffSec"].as_i64().unwrap()
        );
        let view = retry_view(state.as_ref(), &policy, utc(case["at"].as_str().unwrap()));
        let expected_view = &case["view"];
        assert_eq!(
            view.is_some(),
            !expected_view.is_null(),
            "view presence {:?}",
            task
        );
        let Some(view) = view else { continue };
        if expected_view["valid"].as_bool() == Some(false) {
            // Python omits ready/waiting/exhausted entirely for an invalid
            // retryEligibleAt; consumers branch on the error. The port keeps
            // the fields false so no row can look runnable by accident.
            assert!(view.error.is_some(), "error {:?}", task);
            assert!(
                !view.ready && !view.waiting && !view.exhausted,
                "flags {:?}",
                task
            );
            continue;
        }
        let expected = expected_view.as_object().expect("view object");
        assert_eq!(
            view.ready,
            expected["ready"].as_bool().unwrap(),
            "ready {:?}",
            task
        );
        assert_eq!(
            view.waiting,
            expected["waiting"].as_bool().unwrap(),
            "waiting {:?}",
            task
        );
        assert_eq!(
            view.exhausted,
            expected["exhausted"].as_bool().unwrap(),
            "exhausted {:?}",
            task
        );
        assert_eq!(
            view.retry_attempt,
            expected["retryAttempt"].as_i64().unwrap(),
            "retryAttempt {:?}",
            task
        );
        assert_eq!(
            view.retry_eligible_at.as_deref(),
            expected["retryEligibleAt"].as_str(),
            "retryEligibleAt {:?}",
            task
        );
        assert_eq!(
            view.error.is_some(),
            expected["error"].is_string(),
            "error {:?}",
            task
        );
    }
}

#[test]
fn golden_retry_delays_match_the_reference() {
    for case in fixture()["delayCases"].as_array().expect("delayCases") {
        let spec: Option<RetryPolicySpec> =
            Some(serde_json::from_value(case["policy"].clone()).expect("policy shape"));
        let policy = RetryPolicy::from_spec(spec.as_ref());
        for (attempt, expected) in case["delays"].as_object().expect("delays map") {
            let delay = retry_delay(&policy, attempt.parse::<i64>().expect("attempt key"));
            assert_eq!(delay, expected.as_i64().unwrap(), "delay {attempt}");
        }
    }
}
